using System;
using System.Collections;
using System.Collections.Generic;
using TMPro;
using UnityEngine;
using UnityEngine.UI;
using System.Linq;
using static System.Net.Mime.MediaTypeNames;
public class StroopTestManager : MonoBehaviour
{
    // Game elements
    public TMP_Text colorText;
    public Button startButton;
    public Button next;
    public Button back;


    //timer 
    private List<float> events;
    private List<EventTime> eventTimes;
    private List<EventTime> triggerTimes; //Trigger generated by the keyboard space bar
    private int numTrials;
    private int maxTrials = 30; 
    private int numeBlocks;
    private int maxBloks = 2;
    private float trialSecs;
    private float timeElapsed;

    //Stroop test variables
    public Boolean dualTask; 
    private List<Color> colors;
    private List<String> colorNames;
    private List<String> neutralNames;
    public float yellowProbability = 0.67f;

    private enum Conditions { Congruent, Incongruent, Neutral };
    // Access an enum by index: Conditions c = (Conditions)index;

    void Start()
    {
        events = new List<float>();
        eventTimes = new List<EventTime>();

        //Button and gameObjects
        startButton.gameObject.SetActive(true);
        colorText.gameObject.SetActive(false);
        startButton.onClick.AddListener(startTimer);
        back.gameObject.SetActive(false);
        next.gameObject.SetActive(false);
        back.onClick.AddListener(BackToMenu);
        next.onClick.AddListener(NextExperiment);

        //set parameters
        numTrials = 0;
        timeElapsed = 0;
 
        //The yellow color must go at the end of the list
        //The lists should be of the same length
        colors = new List<Color> { Color.red, Color.green, Color.blue, Color.yellow};
        neutralNames = new List<String> { "@@@@@@", "######", "%%%%%%", "$$$$$$$" };

        if (dualTask)
        {
            colorNames = new List<String> { "GRASP", "FLEX", "EXTEND", "ABDUCT" };
            trialSecs = 5f;
        }
        else
        {
            triggerTimes = new List<EventTime>();
            colorNames = new List<String> { "RED", "GREEN", "BLUE", "YELLOW" };
            trialSecs = 3f;
        }


    }

    public void startTimer()
    {
        startButton.gameObject.SetActive(false);
        colorText.gameObject.SetActive(true);
        StartCoroutine(Timer());
        StartCoroutine(ShowColorRutine());
    }

    //Corrutina para controlar el tiempo de juego 
    IEnumerator ShowColorRutine()
    {
        yield return new WaitForSeconds(5f);
        while (numeBlocks < maxBloks)
        {
            while (numTrials < maxTrials)
            {
                //Decide whether the trial will be congruent, incongruent or neutral
                int c = UnityEngine.Random.Range(0, 3); 
                Conditions condition = (Conditions)c;

                // Decide whether to show yellow or not
                int colorIndex;
                bool showYellow = UnityEngine.Random.value <= yellowProbability;
                if (showYellow)
                {
                    colorIndex = colors.Count - 1; // Índice de amarillo
                }
                else
                {
                    // Choose a color different from yellow
                    colorIndex = UnityEngine.Random.Range(0, colors.Count - 1);
                }

                //Select color name and font depending on the condition. 
                if (condition == Conditions.Congruent)
                {
                    //Congruent condition
                    colorText.text = colorNames[colorIndex];
                    colorText.color = colors[colorIndex];
                    //Debug.Log($"Trial Condition: {condition}. Word: {colorNames[colorIndex]} in color {colors[colorIndex]}");
                }
                else if(condition == Conditions.Incongruent)
                {
                    int nameIndex = -1; 
                    //Incongruent condition
                    
                    // Filter the colorNames list to exclude the color name of the selected color font
                    //Exclude the name at index colorIndex
                    List<string> filteredNames = colorNames.Where((name, idx) => (idx != colorIndex)).ToList();
                    nameIndex = UnityEngine.Random.Range(0, filteredNames.Count);
                    //Debug.Log($"Index: {nameIndex}");
                    //Debug.Log($"Trial Condition: {condition}. Word: {filteredNames[nameIndex]} in color {colors[colorIndex]}");

                    colorText.color = colors[colorIndex];
                    colorText.text = filteredNames[nameIndex];
                }
                else if(condition == Conditions.Neutral)
                {
                    colorText.color = colors[colorIndex];
                    colorText.text = neutralNames[colorIndex];
                    //Debug.Log($"Trial Condition: {condition}. Word: {neutralNames[colorIndex]} in color {colors[colorIndex]}");
                }

                yield return new WaitForSecondsRealtime(1f);

                //After 1 second of color display, if the color presented is yellow, save the time event
                float contractionStart = 0; 
                if (showYellow)
                {
                    contractionStart = timeElapsed;
                }
                yield return new WaitForSecondsRealtime(trialSecs-1);

                //TODO: save event times
                if (showYellow) {
                    saveTimeEvent(contractionStart, timeElapsed - contractionStart, condition);
                }
                
                //5 seconds of resting time
                colorText.text = "X";
                colorText.color = Color.white;
                yield return new WaitForSecondsRealtime(trialSecs-1);

                numTrials++;
                Debug.Log($"Num Trials: {numTrials}");
            }
            numTrials = 0;
            numeBlocks++;
            colorText.text = "Break Time";
            yield return new WaitForSecondsRealtime(60f);
        }
        colorText.gameObject.SetActive(false);
        endTask();
    }

    IEnumerator Timer()
    {
        float startTime = Time.realtimeSinceStartup;
        while (numTrials <= 30) {
            yield return new WaitForSecondsRealtime(1f);
            timeElapsed = Time.realtimeSinceStartup - startTime;
        }
    }

    private void saveTimeEvent(float onset, float duration, Conditions condition)
    {
        EventTime ev = new EventTime(onset, duration, condition.ToString());
        eventTimes.Add(ev);
        events.Add(timeElapsed);
        //Debug.Log($"Event at time: {timeElapsed}");
        Debug.Log($"EventTime: {ev}"); 
    }
    private void endTask()
    {
        StopAllCoroutines();

        if(dualTask) GameManager._instance.SaveEventsToCSV(eventTimes, "MCTRelated");
        else GameManager._instance.SaveEventsToCSV(eventTimes, "cognitive");

        next.gameObject.SetActive(true);
        back.gameObject.SetActive(true);
    }

    private void OnApplicationQuit()
    {
        endTask();
    }

    public void BackToMenu()
    {
        GameManager._instance.ChangeScene(GameManager.Scenes.Menu);
    }

    public void NextExperiment()
    {
        if (dualTask)
        {
            //Finish protocol
            GameManager._instance.ChangeScene(GameManager.Scenes.MCTUnrelated);
        }
        else
        {
            //Continue to Cognitive task 
            GameManager._instance.ChangeScene(GameManager.Scenes.MCTRelated);
        }

    }
}
